#!/bin/bash

for site in `ls -1 /etc/letsencrypt/live`; do
    cat /etc/letsencrypt/live/$site/privkey.pem \
      /etc/letsencrypt/live/$site/fullchain.pem \
      | tee /etc/haproxy/certs/haproxy-"$site".pem >/dev/null
done
