#!/bin/bash

if [ -n "${GENERATE_SSL}" ] && [ 1 == "${GENERATE_SSL}" ]; then
    if [ -n "${CERTS}" ]; then
        certbot certonly --no-self-upgrade -n --text --webroot -w /var/lib/haproxy \
            --preferred-challenges http-01 \
            -d "${CERTS}" --keep --expand --agree-tos --email "${EMAIL}" \
            || exit 1

        mkdir -p /etc/haproxy/certs
        for site in `ls -1 /etc/letsencrypt/live`; do
            cat /etc/letsencrypt/live/$site/privkey.pem \
              /etc/letsencrypt/live/$site/fullchain.pem \
              | tee /etc/haproxy/certs/haproxy-"$site".pem >/dev/null
        done
    fi
else
    echo "If you want to generate SSL certs you need to set env GENERATE_SSL=1"
fi

